In [1]:
import numpy as np

In [2]:
a = np.array([[1,0,5], [2,4,7]])

In [3]:
a.shape

(2, 3)

In [5]:
a.ndim

2

In [4]:
b = np.array([[5,3,2], [6,1,4]])

In [7]:
a+b

array([[ 6,  3,  7],
       [ 8,  5, 11]])

In [12]:
a * b

array([[ 5,  0, 10],
       [12,  4, 28]])

In [19]:
b.dot(a.T)

array([[15, 36],
       [26, 44]])

In [18]:
print(a.T.shape)
print(b.shape)

(3, 2)
(2, 3)


In [23]:
a2 = a.reshape(-1, 6)
print(a2)
print(a2.reshape(-1, 3))

[[1 0 5 2 4 7]]
[[1 0 5]
 [2 4 7]]


In [32]:
a1 = np.array([[-4,3], [7,4]])

In [33]:
np.dot(np.linalg.inv(a1),a1)

array([[ 1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [34]:
a1.dot(np.linalg.inv(a1))

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])

array([[-4,  3],
       [ 7,  4]])

In [37]:
class Node:
    def __init__(self, data, next=None):
        self.data = data
        self.next = next 

class Queue:
    def __init__(self):
        self.front = None 
        self.rear = None 
        self._size = 0 

    def enqueue(self, item):
        self._size += 1
        node = Node(item)
        if self.rear is None:
            self.front = node 
            self.rear = node 
        else:
            self.rear.next = node 
            self.rear = node 

    def dequeue(self):
        if self.front is None:
            raise IndexError('pop from empty queue')
        self._size -= 1 
        temp = self.front 
        self.front = self.front.next 
        if self.front is None:
            self.rear = None 
        return temp.data 
    
    def size(self):
        return self._size 

In [38]:
queue = Queue()
queue.enqueue(1)
queue.enqueue(2)
queue.enqueue(3)
queue.enqueue(4)
for i in range(3):
    print(queue.dequeue())

1
2
3


In [43]:
from collections import deque
import time 

lst = list(range(100000))
dq = deque(range(100000))


# pop 성능 
start_time = time.time()
for i in range(100000):
	lst.pop(0)
print(time.time() - start_time)


start_time = time.time()
for i in range(100000):
	dq.popleft()
print(time.time() - start_time)


13.26253366470337
0.006349802017211914


In [44]:
from collections import deque 

queue = deque()

queue.append(1)
queue.append(2)
queue.append(3)

# 큐의 맨 앞 데이터 제거 
first_item = queue.popleft()
print(first_item)

# 큐에 데이터 추가 
queue.append(4)
queue.append(5) 

# 큐의 맨 앞 데이터 제거 
first_item = queue.popleft()
print(frist_item)

1


NameError: name 'frist_item' is not defined